# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=40)),
                ('production_year', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('fuel_level', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Aircraft_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_Type', models.CharField(max_length=25)),
                ('max_fuel_capacity', models.IntegerField()),
                ('first_class_seats', models.IntegerField()),
                ('business_class_seats', models.IntegerField()),
                ('economy_class_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('is_civilian', models.BooleanField()),
                ('is_military', models.BooleanField()),
                ('is_international', models.BooleanField()),
                ('remarks', models.CharField(max_length=500)),
                ('fuel_cost', models.IntegerField()),
                ('fuel_currency', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizedTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aircraft_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Aircraft_Type')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Airport')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Country'),
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.City'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='aircraft_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Aircraft_Type'),
        ),
        migrations.AddField(
            model_name='aircraft',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad.Airport'),
        ),
    ]
