# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='fuel_cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airport',
            name='fuel_currency',
            field=models.CharField(max_length=500),
        ),
    ]
