# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0003_auto_20180710_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizedtypes',
            name='aircraft_type',
        ),
        migrations.RemoveField(
            model_name='authorizedtypes',
            name='airport',
        ),
        migrations.AddField(
            model_name='aircraft_type',
            name='authorized_airports',
            field=models.ManyToManyField(related_name='authorized_aircraft_types', to='ad.Airport'),
        ),
        migrations.DeleteModel(
            name='AuthorizedTypes',
        ),
    ]
